FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Calculus

Polls is a simple API allowing consumers to view polls and vote in them.

## Calculator Collection [/calculator]

### Add an Operation [POST]

+ Request Create New Operation (application/json)

+ Response 201 (application/json)
    + Attributes (Operation)
    
+ Response 405
    Invalid Input
    + Body

## Calculator Collection [/calculator/{operationId}]

+ Parameters
    + operationId (number, required) - Operation Identification

### Update Operation [PUT]
    
+ Request (application/json)
    + Attributes (Operation)

+ Response 202 (application/json)
    + Attributes (Operation)
    Successful Update Operation
    
+ Response 400 (plain)
    Invalid ID Supplied
    + Body
    
+ Response 404
    Operation not Found
    + Body
    
+ Response 405
    Validation Exception
    + Body 

### Delete Operation [DELETE]

+ Response 202 (application/json)
    + Attributes (Operation)
    Successful Delete Operation
    
+ Response 400 
    Invalid ID Supplied
    + Body
    
+ Response 404
    Operation not Found
    + Body
    
+ Response 405
    Validation Exception
    + Body
   
### Obtain Operation [GET]


+ Response 200 (application/json)
    + Attributes (Operation)
    Successful Operation
    
+ Response 400 
    Invalid Tag Value
    + Body

## Override Collection [/calculator/{operationId}/deleteOperation]

+ Parameters
    + operationId (number, required) - Operation Identification

### Override Delete Operation on GET HTTP Verb [GET]
            
+ Response 200 (application/json)
    + Attributes (Operation)
    Successful Operation

+ Response 400
    Invalid Tag Value
    + Body

## Calculation Collection [/calculator/calculate/{?operand1,operand2,operator}]

### Calculate [GET]
           
+ Parameters
    + operand1: 10 (number, required) - First Operand 
    + operand2: 20 (number, required) - Second Operand
    + operator: Addition (string, required) - Operator Multiplication, Division, Subtraction or Addition
    
            
+ Response 200 (application/json)
    + Attributes (Operation)
    Successful Operation

+ Response 400
    Invalid Tag Value
    + Body

## Data Structures

### Operation (object)
+ operationId: 10 (number, required) - Operation Identification on Db
+ operand1: 10 (number, required) - First Operand 
+ operand2: 20 (number, required) - Second Operand
+ operator: Addition (string, required) - Operator Multiplication, Division, Subtraction or Addition
+ result: 30 (number, required) - Result